-- CASO 1
CREATE TABLE RECAUDACION_BONOS_MEDICOS (
    RUT_MEDICO      VARCHAR2(20),
    NOMBRE_MEDICO   VARCHAR2(200),
    TOTAL_RECAUDADO NUMBER,
    UNIDAD_MEDICA   VARCHAR2(100)
);

INSERT INTO RECAUDACION_BONOS_MEDICOS (RUT_MEDICO, NOMBRE_MEDICO, TOTAL_RECAUDADO, UNIDAD_MEDICA)
SELECT 
    REGEXP_REPLACE(M.RUT_MED || '-' || M.DV_RUN, '^([0-9]{1,3})([0-9]{3})([0-9]{3})-', '\1.\2.\3-')
        AS RUT_MEDICO,
    INITCAP(M.PNOMBRE || ' ' || M.APATERNO || ' ' || M.AMATERNO)
        AS NOMBRE_MEDICO,
    ROUND(SUM(B.COSTO))
        AS TOTAL_RECAUDADO,
    INITCAP(U.NOMBRE)
        AS UNIDAD_MEDICA
FROM 
    MEDICO M
    JOIN BONO_CONSULTA B ON M.RUT_MED = B.RUT_MED
    JOIN UNIDAD_CONSULTA U ON M.UNI_ID = U.UNI_ID
WHERE 
    EXTRACT(YEAR FROM B.FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND M.CAR_ID NOT IN (100, 500, 600)
GROUP BY 
    M.RUT_MED, M.DV_RUN, M.PNOMBRE, M.APATERNO, M.AMATERNO, U.NOMBRE
ORDER BY 
    SUM(B.COSTO) ASC;
COMMIT;

--  RESULTADO CASO 1
SELECT 
    RUT_MEDICO                                                          AS "RUT MÉDICO",
    NOMBRE_MEDICO                                                       AS "NOMBRE MÉDICO",
    '$' || TRIM(TO_CHAR(TOTAL_RECAUDADO, 'FM999G999G999', 'NLS_NUMERIC_CHARACTERS='',.'''))
                                                                        AS "TOTAL RECAUDADO",
    UNIDAD_MEDICA                                                       AS "UNIDAD MÉDICA"
FROM RECAUDACION_BONOS_MEDICOS
ORDER BY TOTAL_RECAUDADO ASC;


-- CASO 2
SELECT 
    INITCAP(EM.NOMBRE)                           AS "ESPECIALIDAD MÉDICA",
    COUNT(B.ID_BONO)                             AS "CANTIDAD BONOS",
    '$' || TRIM(TO_CHAR(ROUND(SUM(B.COSTO)), 'FM999G999G999', 'NLS_NUMERIC_CHARACTERS='',.'''))
                                                 AS "MONTO PÉRDIDA",
    TO_CHAR(MIN(B.FECHA_BONO), 'DD-MM-YYYY')     AS "FECHA BONO",
    CASE 
        WHEN EXTRACT(YEAR FROM MIN(B.FECHA_BONO)) >= EXTRACT(YEAR FROM SYSDATE) - 1 
        THEN 'COBRABLE'
        ELSE 'INCOBRABLE'
    END                                          AS "ESTADO DE COBRO"
FROM 
    BONO_CONSULTA B
    JOIN ESPECIALIDAD_MEDICA EM ON B.ESP_ID = EM.ESP_ID
WHERE B.ID_BONO IN (
    SELECT ID_BONO FROM BONO_CONSULTA
    MINUS
    SELECT ID_BONO FROM PAGOS
)
GROUP BY 
    EM.NOMBRE
ORDER BY 
    COUNT(B.ID_BONO) ASC,
    SUM(B.COSTO) DESC;
    


-- CASO 3
INSERT INTO CANT_BONOS_PACIENTES_ANNIO 
    (ANNIO_CALCULO, PAC_RUN, DV_RUN, EDAD, CANTIDAD_BONOS, MONTO_TOTAL_BONOS, SISTEMA_SALUD)
SELECT
    EXTRACT(YEAR FROM SYSDATE)                               AS ANNIO_CALCULO,
    P.PAC_RUN                                                AS PAC_RUN,
    P.DV_RUN                                                 AS DV_RUN,
    ROUND(MONTHS_BETWEEN(SYSDATE, P.FECHA_NACIMIENTO) / 12)  AS EDAD,
    COUNT(B.ID_BONO)                                         AS CANTIDAD_BONOS,
    ROUND(NVL(SUM(B.COSTO), 0))                              AS MONTO_TOTAL_BONOS,
    UPPER(SS.DESCRIPCION)                                    AS SISTEMA_SALUD
FROM 
    PACIENTE P
    JOIN SALUD S ON P.SAL_ID = S.SAL_ID
    JOIN SISTEMA_SALUD SS ON S.TIPO_SAL_ID = SS.TIPO_SAL_ID
    LEFT JOIN BONO_CONSULTA B 
        ON P.PAC_RUN = B.PAC_RUN
        AND EXTRACT(YEAR FROM B.FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1
WHERE 
    SS.TIPO_SAL_ID IN ('F', 'FA', 'P')
GROUP BY 
    P.PAC_RUN, P.DV_RUN, P.FECHA_NACIMIENTO, SS.DESCRIPCION
HAVING 
    COUNT(B.ID_BONO) <= (
        SELECT ROUND(AVG(CANT_BONOS))
        FROM (
            SELECT COUNT(ID_BONO) AS CANT_BONOS
            FROM BONO_CONSULTA
            WHERE EXTRACT(YEAR FROM FECHA_BONO) = EXTRACT(YEAR FROM SYSDATE) - 1
            GROUP BY PAC_RUN
        )
    )
ORDER BY 
    MONTO_TOTAL_BONOS ASC,
    EDAD DESC;

COMMIT;

-- RESULTADO CASO 3
SELECT * FROM CANT_BONOS_PACIENTES_ANNIO
WHERE ANNIO_CALCULO = EXTRACT(YEAR FROM SYSDATE)
ORDER BY MONTO_TOTAL_BONOS ASC, EDAD DESC;

